Validation added
HRIS-M/HRIS pull request #154
Opened 2024-04-16 11:03 UTC by RainiWijewantha

Only Job Post Module

2024-04-16 13:11 UTC, kavicastelo requested changes
Provide answers and change requested changes. If you are facing any problems with that, contact me.

2024-04-16 13:11 UTC, kavicastelo commented on src/main/java/com/hris/HRIS/service/JobPostService.java
> +        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
Using regex for validation is a bit of an advanced and I think you tested this pattern before opening the PR. Regex is are bit complicated to handle in different scenarios. As an example, the email validation pattern is different in Java and C or Java and Javascript.
`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$`
To my knowledge, you allowed simple and capital letters, 0-9 numbers, and a couple of special characters (._%+-) for the first element. We know commonly we need to add `\` before special characters we going to accept. Then you'll check the email containing the `@` symbol. Then you try to allow all English characters and dot and hyphen symbols for the next element (gmail, yahoo). then you checking the dot is contained or not. After that, I see you allowing the final element to be only 2 characters. How do you allow (com) emails using 2 chars?

2024-04-17 17:26 UTC, RainiWijewantha commented
Ok, I'll change

2024-04-25 06:03 UTC, kavicastelo commented
You're spending too much time to complete your requested changes. Your PR marked as red because your PR not made any changes within 4 business days. Hurry up!!
@RainiWijewantha

2024-05-07 15:58 UTC, closed without merging