Pawara
HRIS-M/HRIS pull request #36
Opened 2024-02-24 04:38 UTC by PawaraLiyanage

2024-02-24 09:07 UTC, kavicastelo requested changes
Complete the control methods and check out the request changes. Recommended to add CRUD operations minimally.

2024-02-24 09:07 UTC, kavicastelo commented on pom.xml
> +            <groupId>org.apache.xbean</groupId>
Seems this is unnecessary for this PR. If you need to add this dependency please explain why.

2024-02-24 09:07 UTC, kavicastelo commented on src/main/java/com/hris/HRIS/controller/AttendanceController.java
> +    public void getId(){
don't need to create a method to get ID. Mongo repository already supplies you with pre-defined methods to handle collection data with ID.

2024-02-24 09:56 UTC, kavicastelo requested changes
need to change repository methods

2024-02-24 09:56 UTC, kavicastelo commented on src/main/java/com/hris/HRIS/repository/AttendanceRepository.java
> +    Optional<AttendanceModel> findByEmail(String email);
you cannot use this custom method here. you can only handle custom methods according to your collection model

2024-02-24 09:56 UTC, kavicastelo commented on src/main/java/com/hris/HRIS/repository/AttendanceRepository.java
> +    Optional<AttendanceModel> deleteByEmail(String email);
same as the `findByEmail` method. if you need to use a method like this, you need to have an email field in your model. In your case, you can use,
- findByInTime
- FindAllByInTime
- deleteByOutTime
- and blah blah...

2024-02-29 16:06 UTC, PawaraLiyanage reviewed
Updated

2024-02-29 16:07 UTC, PawaraLiyanage commented on src/main/java/com/hris/HRIS/controller/AttendanceController.java
> +    public void getId(){
done

2024-02-29 16:56 UTC, kavicastelo approved these changes
reviewed and approved
`changed the pom.xml` typo conflict.

Make sure to update your local repository before contributing next time
*remove unwanted space and add tab line 57 in pom.xml*

2024-02-29 16:56 UTC, merged