Open User register and login
HRIS-M/HRIS pull request #48
Opened 2024-02-28 19:08 UTC by RainiWijewantha

2024-02-28 19:12 UTC, kavicastelo requested changes
make change the requested changes

2024-02-28 19:12 UTC, kavicastelo commented on pom.xml
> +            <plugin>
this is an unnecessary part.
if you need to add this, provide me a reason

2024-02-29 17:14 UTC, RainiWijewantha commented on pom.xml
> +            <plugin>
It happens with my IDE. I will try to solve this problem immediately.

2024-03-01 14:42 UTC, kavicastelo approved these changes
reviewed and approved

2024-03-01 14:42 UTC, merged

2024-03-01 21:28 UTC, kavicastelo commented on pom.xml
> +            <plugin>
use compatible java versions