[New] : Functionality to add ETF deductions to the payitems entity
HRIS-M/HRIS pull request #77
Opened 2024-03-03 15:08 UTC by Himashana2

2024-03-04 10:32 UTC, kavicastelo requested changes
I found a couple of wrong APIs in your control and need to be replaced. 
you tried to send requests like this
`/api/v1/employee/payitems{email}/EPFdeductions`

These types of APIs will be complicated to handle further you need to separate request params from the request API
correct way
`/api/v1/employee/payitems/{email}/EPFdeductions`

Request changes need to be applied in next PR @Himashana2

2024-03-04 10:32 UTC, kavicastelo commented on src/main/java/com/hris/HRIS/controller/EmployeePayItemController.java
> +    @PostMapping("{email}/EPFdeductions")
replace endpoint with this
`/{email}/EPFdeductions`

2024-03-07 08:44 UTC, kavicastelo reviewed
Changes are approved. 

Explain to me why you added a new npm package called `array-flatten` to the client side.

2024-03-07 09:58 UTC, Himashana2 commented
> Changes are approved.
> 
> Explain to me why you added a new npm package called `array-flatten` to the client side.

When I'm trying to run the angular application, it shows an error because it says "array-flatten" is missing... an error something like that. So, I installed it.

2024-03-07 11:29 UTC, kavicastelo commented
> > Changes are approved.
> > Explain to me why you added a new npm package called `array-flatten` to the client side.
> 
> When I'm trying to run the angular application, it shows an error because it says "array-flatten" is missing... an error something like that. So, I installed it.

*Interesting!*
Thank you for providing details

2024-03-07 11:29 UTC, merged